### ISSUE TITLE
Audio visualiser has lingering lighting effects

### ISSUE THREAD

**Issue by wu4x** [Aurora-RGB/Aurora#54] opened 2022-06-13 13:25 UTC
![afbeelding](https://user-images.githubusercontent.com/89080561/173363510-9ddff643-20b1-4cc7-a7af-3c339f539137.png)
Attached image is what the equaliser preview displays

### Expected Behaviour
I'm playing some sort of audio, the audio visualiser visualises that audio and gives me cool effects.
Then when I turn off that audio, the audio visualisation layer stops.

### Actual Behaviour
I play audio and I get cool effects.
But when I then turn off that audio (whole pc is silent, no application is producing audio) the audio visualisation layer keeps displaying some audio linger for a couple seconds or longer (depends).

### Reproduction steps
Step 1: have audio visualisation layer
Step 2: Play Audio
Step 3: Turn off Audio
Step 4: Watch as audio lingers for a couple seconds or longer

### Frequency
Every time

### Aurora Version:
The latest version V49

### Previously an Issue?
I don't know

**Comment by Aytackydln** [comment] 2022-06-19 12:36
Hello, I've tried to reproduce this but couldn't. Can you share me your layer settings screenshot?

**Comment by wu4x** [comment] 2022-06-19 12:54
![afbeelding](https://user-images.githubusercontent.com/89080561/174481844-409c25fd-c58e-4de0-91c8-7508c6cd9d56.png)
These are the settings I use, however the bug randomly fixed itself for me and I cannot reproduce it anymore. I haven't changed anything so I really don't know why it's fixed

**Comment by Aytackydln** [comment] 2022-06-28 11:21
can you share your logs right after this happens?

**Comment by wu4x** [comment] 2022-06-28 16:21
[2022-06-28 18.18.31.log](https://github.com/Aurora-RGB/Aurora/files/9002863/2022-06-28.18.18.31.log)

**Comment by Aytackydln** [comment] 2022-12-07 13:35
Audio visualiser behaviour changed since the issue was opened. Can you check again?

**Comment by Aytackydln** [comment] 2022-12-07 19:56
Also, if it is still not fixed you can use overrides to disable the layer if there is no media playing.

I will close the issue for now

**Closed by Aytackydln** 2022-12-07 19:56 UTC
Labels: Type: Bug
